### ISSUE TITLE
Malformed Url error when executing

### ISSUE THREAD

**Issue by nicolasTorrell** [kungfu-king-betty/cordova-plugin-native-app-update#4]
## Your Environment
* Plugin version: 1.0.3
* Platform: Android
* OS version: 8.0.0
* Device manufacturer / model: Samsung
* Cordova version (`cordova -v`): 8.1.2
* Cordova platform version (`cordova platform ls`): 8.0.0
* Plugin config

## Expected Behavior
Should check with needs update and show a dialog

## Actual Behavior
gives error: java.lang.IllegalArgumentException: Malformed URL: null
	at org.jsoup.helper.HttpConnection.url(HttpConnection.java:78)
	at org.jsoup.helper.HttpConnection.connect(HttpConnection.java:38)
	at org.jsoup.Jsoup.connect(Jsoup.java:73)
	at com.kungfukingbetty.cordova.appupdate.CDVAppUpdate.needsUpdate(CDVAppUpdate.java:189)
	at com.kungfukingbetty.cordova.appupdate.CDVAppUpdate.execute(CDVAppUpdate.java:66)
	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:117)
	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
	at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:325)
	at android.os.Looper.loop(Looper.java:142)
	at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: java.net.MalformedURLException: no protocol: null
	at java.net.URL.<init>(URL.java:590)
	at java.net.URL.<init>(URL.java:487)
	at java.net.URL.<init>(URL.java:436)
	at org.jsoup.helper.HttpConnection.url(HttpConnection.java:76)
	... 13 more

## Steps to Reproduce
1. Just executes this code when opening app
  AppUpdate.needsUpdate(function(appUpdateObj) {
        if(appUpdateObj.update_available == 1) {
          console.log("There is New Version of this application available,Click Upgrade to Update now ?");
            navigator.notification.confirm("Hay verión nueva en la tienda, quieres actualizar tu aplicación?", onConfirm, "", ["Actualizar","Cancelar"]);                    
        }
    }, function(error){
        console.log("App Update ERROR:",error);
    });

## Context
Check playstore verios

## Debug logs
2021-08-02 12:40:19.440 12611-12611/com.tecnogeo.participa.ordino W/SELinux: SELinux selinux_android_compute_policy_index : Policy Index[2],  Con:u:r:zygote:s0 RAM:SEPF_SM-G935F_8.0.0_0018, [-1 -1 -1 -1 0 1]
2021-08-02 12:40:19.441 12611-12611/com.tecnogeo.participa.ordino I/SELinux: SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=com.tecnogeo.participa.ordino 
2021-08-02 12:40:19.446 12611-12611/com.tecnogeo.participa.ordino I/zygote64: Late-enabling -Xcheck:jni
2021-08-02 12:40:19.501 12611-12611/com.tecnogeo.participa.ordino D/ActivityThread: Added TimaKeyStore provider
2021-08-02 12:40:19.552 12611-12611/com.tecnogeo.participa.ordino I/zygote64: no shared libraies, dex_files: 1
2021-08-02 12:40:19.585 12611-12611/com.tecnogeo.participa.ordino I/MultiDex: VM with version 2.1.0 has multidex support
2021-08-02 12:40:19.585 12611-12611/com.tecnogeo.participa.ordino I/MultiDex: Installing application
2021-08-02 12:40:19.585 12611-12611/com.tecnogeo.participa.ordino I/MultiDex: VM has multidex support, MultiDex support library is disabled.
2021-08-02 12:40:19.591 12611-12611/com.tecnogeo.participa.ordino D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
2021-08-02 12:40:19.599 12611-12611/com.tecnogeo.participa.ordino D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
2021-08-02 12:40:19.609 12611-12611/com.tecnogeo.participa.ordino I/FirebaseInitProvider: FirebaseApp initialization successful
2021-08-02 12:40:19.625 12611-12636/com.tecnogeo.participa.ordino I/FA: App measurement is starting up, version: 11720
2021-08-02 12:40:19.625 12611-12636/com.tecnogeo.participa.ordino I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
2021-08-02 12:40:19.625 12611-12636/com.tecnogeo.participa.ordino I/FA: To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app com.tecnogeo.participa.ordino
2021-08-02 12:40:19.638 12611-12611/com.tecnogeo.participa.ordino I/CordovaLog: Changing log level to DEBUG(3)
2021-08-02 12:40:19.638 12611-12611/com.tecnogeo.participa.ordino I/CordovaActivity: Apache Cordova native platform version 8.0.0 is starting
2021-08-02 12:40:19.638 12611-12611/com.tecnogeo.participa.ordino D/CordovaActivity: CordovaActivity.onCreate()
2021-08-02 12:40:19.651 12611-12611/com.tecnogeo.participa.ordino I/zygote64: no shared libraies, dex_files: 1
2021-08-02 12:40:19.657 12611-12611/com.tecnogeo.participa.ordino I/WebViewFactory: Loading com.android.chrome version 92.0.4515.115 (code 451511523)
2021-08-02 12:40:19.705 12611-12611/com.tecnogeo.participa.ordino I/cr_WVCFactoryProvider: Loaded version=92.0.4515.115 minSdkVersion=24 isBundle=true multiprocess=true packageId=2
2021-08-02 12:40:19.737 12611-12611/com.tecnogeo.participa.ordino I/cr_LibraryLoader: Successfully loaded native library
2021-08-02 12:40:19.739 12611-12611/com.tecnogeo.participa.ordino I/cr_CachingUmaRecorder: Flushed 8 samples from 8 histograms.
2021-08-02 12:40:19.758 12611-12644/com.tecnogeo.participa.ordino W/ResourceType: Failure getting entry for 0x7f130796 (t=18 e=1942) (error -2147483647)
2021-08-02 12:40:19.846 12611-12611/com.tecnogeo.participa.ordino D/ConnectivityManager: requestNetwork; CallingUid : 10229, CallingPid : 12611
2021-08-02 12:40:19.895 12611-12611/com.tecnogeo.participa.ordino D/SystemWebViewEngine: CordovaWebView is running on device made by: samsung
2021-08-02 12:40:19.900 12611-12611/com.tecnogeo.participa.ordino D/PluginManager: init()
2021-08-02 12:40:19.915 12611-12611/com.tecnogeo.participa.ordino D/FileUtils: Unrecognized extra filesystem identifier: assets
2021-08-02 12:40:19.970 12611-12683/com.tecnogeo.participa.ordino D/OpenGLRenderer: HWUI GL Pipeline
2021-08-02 12:40:19.977 12611-12611/com.tecnogeo.participa.ordino D/ViewRootImpl@4a312d9[MainActivity]: setView = DecorView@603549e[] TM=true MM=false
2021-08-02 12:40:20.010 12611-12616/com.tecnogeo.participa.ordino I/zygote64: Do partial code cache collection, code=30KB, data=23KB
2021-08-02 12:40:20.010 12611-12616/com.tecnogeo.participa.ordino I/zygote64: After code cache collection, code=30KB, data=23KB
2021-08-02 12:40:20.010 12611-12616/com.tecnogeo.participa.ordino I/zygote64: Increasing code cache capacity to 128KB
2021-08-02 12:40:20.017 12611-12611/com.tecnogeo.participa.ordino D/ScrollView: initGoToTop
2021-08-02 12:40:20.024 12611-12611/com.tecnogeo.participa.ordino D/ScrollView: initGoToTop
2021-08-02 12:40:20.042 12611-12611/com.tecnogeo.participa.ordino D/ViewRootImpl@32015e0[MainActivity]: setView = DecorView@693c099[] TM=true MM=false
2021-08-02 12:40:20.050 12611-12611/com.tecnogeo.participa.ordino D/CordovaWebViewImpl: >>> loadUrl(file:///android_asset/www/index.html)
2021-08-02 12:40:20.059 12611-12667/com.tecnogeo.participa.ordino W/cr_media: Requires BLUETOOTH permission
2021-08-02 12:40:20.064 12611-12611/com.tecnogeo.participa.ordino D/CordovaActivity: Started the activity.
2021-08-02 12:40:20.085 12611-12611/com.tecnogeo.participa.ordino D/CordovaActivity: Resumed the activity.
2021-08-02 12:40:20.093 12611-12636/com.tecnogeo.participa.ordino I/FA: Tag Manager is not found and thus will not be used
2021-08-02 12:40:20.094 12611-12611/com.tecnogeo.participa.ordino D/ViewRootImpl@603e9d1[MainActivity]: setView = DecorView@98e6c36[MainActivity] TM=true MM=false
2021-08-02 12:40:20.106 12611-12686/com.tecnogeo.participa.ordino D/libGLESv2: STS_GLApi : DTS, ODTC are not allowed for Package : com.tecnogeo.participa.ordino
2021-08-02 12:40:20.144 12611-12611/com.tecnogeo.participa.ordino D/ViewRootImpl@4a312d9[MainActivity]: dispatchAttachedToWindow
2021-08-02 12:40:20.159 12611-12611/com.tecnogeo.participa.ordino V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
2021-08-02 12:40:20.160 12611-12611/com.tecnogeo.participa.ordino D/ViewRootImpl@4a312d9[MainActivity]: Relayout returned: old=[0,0][0,0] new=[0,0][1080,1920] result=0x7 surface={valid=true 502749667328} changed=true
2021-08-02 12:40:20.161 12611-12683/com.tecnogeo.participa.ordino I/OpenGLRenderer: Initialized EGL, version 1.4
2021-08-02 12:40:20.168 12611-12683/com.tecnogeo.participa.ordino D/OpenGLRenderer: Swap behavior 2
2021-08-02 12:40:20.170 12611-12611/com.tecnogeo.participa.ordino D/ViewRootImpl@32015e0[MainActivity]: dispatchAttachedToWindow
2021-08-02 12:40:20.175 12611-12683/com.tecnogeo.participa.ordino D/libGLESv1: STS_GLApi : DTS, ODTC are not allowed for Package : com.tecnogeo.participa.ordino
2021-08-02 12:40:20.177 12611-12683/com.tecnogeo.participa.ordino D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [1080x1920]-format:1
2021-08-02 12:40:20.177 12611-12683/com.tecnogeo.participa.ordino D/OpenGLRenderer: eglCreateWindowSurface = 0x7522216ea0
2021-08-02 12:40:20.208 12611-12611/com.tecnogeo.participa.ordino V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
2021-08-02 12:40:20.209 12611-12611/com.tecnogeo.participa.ordino D/ViewRootImpl@32015e0[MainActivity]: Relayout returned: old=[0,0][0,0] new=[27,924][1053,1068] result=0x27 surface={valid=true 502662139904} changed=true
2021-08-02 12:40:20.212 12611-12683/com.tecnogeo.participa.ordino D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [1218x336]-format:1
2021-08-02 12:40:20.212 12611-12683/com.tecnogeo.participa.ordino D/OpenGLRenderer: eglCreateWindowSurface = 0x7522216ef0
2021-08-02 12:40:20.237 12611-12611/com.tecnogeo.participa.ordino D/ViewRootImpl@603e9d1[MainActivity]: dispatchAttachedToWindow
2021-08-02 12:40:20.249 12611-12611/com.tecnogeo.participa.ordino V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
2021-08-02 12:40:20.250 12611-12611/com.tecnogeo.participa.ordino D/ViewRootImpl@603e9d1[MainActivity]: Relayout returned: old=[0,0][0,0] new=[0,0][1080,1920] result=0x7 surface={valid=true 502662144000} changed=true
2021-08-02 12:40:20.262 12611-12683/com.tecnogeo.participa.ordino D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [1080x1920]-format:1
2021-08-02 12:40:20.262 12611-12683/com.tecnogeo.participa.ordino D/OpenGLRenderer: eglCreateWindowSurface = 0x7522216f40
2021-08-02 12:40:20.268 12611-12611/com.tecnogeo.participa.ordino D/ViewRootImpl@4a312d9[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1
2021-08-02 12:40:20.269 12611-12611/com.tecnogeo.participa.ordino V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@a891c21 nm : com.tecnogeo.participa.ordino ic=null
2021-08-02 12:40:20.269 12611-12611/com.tecnogeo.participa.ordino I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2021-08-02 12:40:20.272 12611-12611/com.tecnogeo.participa.ordino D/ViewRootImpl@32015e0[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1
2021-08-02 12:40:20.276 12611-12611/com.tecnogeo.participa.ordino D/CordovaWebViewImpl: onPageDidNavigate(file:///android_asset/www/index.html)
2021-08-02 12:40:20.342 12611-12611/com.tecnogeo.participa.ordino D/ViewRootImpl@4a312d9[MainActivity]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 1920) ci=Rect(0, 72 - 0, 0) vi=Rect(0, 72 - 0, 0) or=1
2021-08-02 12:40:20.344 12611-12611/com.tecnogeo.participa.ordino D/ViewRootImpl@32015e0[MainActivity]: MSG_RESIZED_REPORT: frame=Rect(27, 924 - 1053, 1068) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
2021-08-02 12:40:20.345 12611-12611/com.tecnogeo.participa.ordino D/ViewRootImpl@603e9d1[MainActivity]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 1920) ci=Rect(0, 72 - 0, 0) vi=Rect(0, 72 - 0, 0) or=1
2021-08-02 12:40:20.347 12611-12611/com.tecnogeo.participa.ordino V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@65faa2a nm : com.tecnogeo.participa.ordino ic=null
2021-08-02 12:40:20.364 12611-12611/com.tecnogeo.participa.ordino D/ViewRootImpl@4a312d9[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0
2021-08-02 12:40:20.466 12611-12611/com.tecnogeo.participa.ordino D/JsMessageQueue: Set native->JS mode to EvalBridgeMode
2021-08-02 12:40:20.475 12611-12611/com.tecnogeo.participa.ordino D/SystemWebChromeClient: file:///android_asset/www/js/libs/jquery-1.8.3.min.js: Line 2 : Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
2021-08-02 12:40:20.475 12611-12611/com.tecnogeo.participa.ordino I/chromium: [INFO:CONSOLE(2)] "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.", source: file:///android_asset/www/js/libs/jquery-1.8.3.min.js (2)
2021-08-02 12:40:20.548 12611-12616/com.tecnogeo.participa.ordino I/zygote64: Do partial code cache collection, code=61KB, data=59KB
2021-08-02 12:40:20.548 12611-12616/com.tecnogeo.participa.ordino I/zygote64: After code cache collection, code=61KB, data=59KB
2021-08-02 12:40:20.548 12611-12616/com.tecnogeo.participa.ordino I/zygote64: Increasing code cache capacity to 256KB
2021-08-02 12:40:20.768 12611-12717/com.tecnogeo.participa.ordino D/NetworkManager: toLower : wifi
2021-08-02 12:40:20.768 12611-12717/com.tecnogeo.participa.ordino D/NetworkManager: wifi : wifi
2021-08-02 12:40:20.768 12611-12717/com.tecnogeo.participa.ordino D/NetworkManager: Connection Type: wifi
2021-08-02 12:40:20.768 12611-12717/com.tecnogeo.participa.ordino D/NetworkManager: Connection Extra Info: "ASUS_5G_47A1"
2021-08-02 12:40:20.791 12611-12611/com.tecnogeo.participa.ordino D/NetworkManager: toLower : wifi
2021-08-02 12:40:20.791 12611-12611/com.tecnogeo.participa.ordino D/NetworkManager: wifi : wifi
2021-08-02 12:40:20.791 12611-12611/com.tecnogeo.participa.ordino D/NetworkManager: Connection Type: wifi
2021-08-02 12:40:20.792 12611-12611/com.tecnogeo.participa.ordino D/NetworkManager: Connection Extra Info: "ASUS_5G_47A1"
2021-08-02 12:40:21.245 12611-12717/com.tecnogeo.participa.ordino I/App: WARNING: Back Button Default Behavior will be overridden.  The backbutton event will be fired!
2021-08-02 12:40:21.254 12611-12611/com.tecnogeo.participa.ordino D/CordovaWebViewImpl: onPageFinished(file:///android_asset/www/index.html)
2021-08-02 12:40:21.265 12611-12718/com.tecnogeo.participa.ordino W/AssetFilesystem: Asset manifest not found. Recursive copies and directory listing will be slow.
2021-08-02 12:40:21.337 12611-12611/com.tecnogeo.participa.ordino D/SystemWebChromeClient: file:///android_asset/www/js/all.js: Line 576 : https://participa.absiscloud.com/ParticipaDevices/RegisterDevice/roleDevice/
2021-08-02 12:40:21.337 12611-12611/com.tecnogeo.participa.ordino I/chromium: [INFO:CONSOLE(576)] "https://participa.absiscloud.com/ParticipaDevices/RegisterDevice/roleDevice/", source: file:///android_asset/www/js/all.js (576)
2021-08-02 12:40:21.343 12611-12611/com.tecnogeo.participa.ordino D/SystemWebChromeClient: file:///android_asset/www/js/all.js: Line 577 : Ordinoesviu
2021-08-02 12:40:21.343 12611-12611/com.tecnogeo.participa.ordino I/chromium: [INFO:CONSOLE(577)] "Ordinoesviu", source: file:///android_asset/www/js/all.js (577)
2021-08-02 12:40:21.346 12611-12611/com.tecnogeo.participa.ordino D/SystemWebChromeClient: file:///android_asset/www/js/all.js: Line 578 : Information response parameters: https://participa.absiscloud.com/ParticipaDevices/RegisterDevice/roleDevice/product=Participa&idPlatformApp=2&idDevice=d942bde9-86bd-4ef8-8ee5-85ca240d5943
2021-08-02 12:40:21.346 12611-12611/com.tecnogeo.participa.ordino I/chromium: [INFO:CONSOLE(578)] "Information response parameters: https://participa.absiscloud.com/ParticipaDevices/RegisterDevice/roleDevice/product=Participa&idPlatformApp=2&idDevice=d942bde9-86bd-4ef8-8ee5-85ca240d5943", source: file:///android_asset/www/js/all.js (578)
2021-08-02 12:40:21.546 12611-12673/com.tecnogeo.participa.ordino D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2021-08-02 12:40:21.846 12611-12717/com.tecnogeo.participa.ordino V/NativeAppUpdate: Init NativeAppUpdate
2021-08-02 12:40:21.848 12611-12717/com.tecnogeo.participa.ordino V/NativeAppUpdate: NativeAppUpdate action: needsUpdate
2021-08-02 12:40:21.849 12611-12611/com.tecnogeo.participa.ordino D/SystemWebChromeClient: file:///android_asset/www/js/all.js: Line 583 : PRO
2021-08-02 12:40:21.849 12611-12611/com.tecnogeo.participa.ordino I/chromium: [INFO:CONSOLE(583)] "PRO", source: file:///android_asset/www/js/all.js (583)
2021-08-02 12:40:21.852 12611-12611/com.tecnogeo.participa.ordino D/SystemWebChromeClient: file:///android_asset/www/js/all.js: Line 591 : PRO
2021-08-02 12:40:21.853 12611-12611/com.tecnogeo.participa.ordino I/chromium: [INFO:CONSOLE(591)] "PRO", source: file:///android_asset/www/js/all.js (591)
2021-08-02 12:40:21.888 12611-12717/com.tecnogeo.participa.ordino I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2021-08-02 12:40:21.890 12611-12717/com.tecnogeo.participa.ordino I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2021-08-02 12:40:22.876 12611-12616/com.tecnogeo.participa.ordino I/zygote64: Do full code cache collection, code=124KB, data=105KB
2021-08-02 12:40:22.876 12611-12616/com.tecnogeo.participa.ordino I/zygote64: After code cache collection, code=111KB, data=60KB
2021-08-02 12:40:22.983 12611-12616/com.tecnogeo.participa.ordino I/zygote64: Do partial code cache collection, code=115KB, data=75KB
2021-08-02 12:40:22.983 12611-12616/com.tecnogeo.participa.ordino I/zygote64: After code cache collection, code=115KB, data=75KB
2021-08-02 12:40:22.983 12611-12616/com.tecnogeo.participa.ordino I/zygote64: Increasing code cache capacity to 512KB
2021-08-02 12:40:23.061 12611-12717/com.tecnogeo.participa.ordino D/NativeAppUpdate: Current version: 1.4.0, Play Store version: 1.7.0
2021-08-02 12:40:23.062 12611-12717/com.tecnogeo.participa.ordino E/NativeAppUpdate: java.lang.IllegalArgumentException: Malformed URL: null
        at org.jsoup.helper.HttpConnection.url(HttpConnection.java:78)
        at org.jsoup.helper.HttpConnection.connect(HttpConnection.java:38)
        at org.jsoup.Jsoup.connect(Jsoup.java:73)
        at com.kungfukingbetty.cordova.appupdate.CDVAppUpdate.needsUpdate(CDVAppUpdate.java:189)
        at com.kungfukingbetty.cordova.appupdate.CDVAppUpdate.execute(CDVAppUpdate.java:66)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:117)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
        at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
        at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.net.MalformedURLException: no protocol: null
        at java.net.URL.<init>(URL.java:590)
        at java.net.URL.<init>(URL.java:487)
        at java.net.URL.<init>(URL.java:436)
        at org.jsoup.helper.HttpConnection.url(HttpConnection.java:76)
        at org.jsoup.helper.HttpConnection.connect(HttpConnection.java:38) 
        at org.jsoup.Jsoup.connect(Jsoup.java:73) 
        at com.kungfukingbetty.cordova.appupdate.CDVAppUpdate.needsUpdate(CDVAppUpdate.java:189) 
        at com.kungfukingbetty.cordova.appupdate.CDVAppUpdate.execute(CDVAppUpdate.java:66) 
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:117) 
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98) 
        at org.apache.cordova.PluginManager.exec(PluginManager.java:132) 
        at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59) 
        at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41) 
        at android.os.MessageQueue.nativePollOnce(Native Method) 
        at android.os.MessageQueue.next(MessageQueue.java:325) 
        at android.os.Looper.loop(Looper.java:142) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
2021-08-02 12:40:23.063 12611-12717/com.tecnogeo.participa.ordino W/CordovaPlugin: Attempted to send a second callback for ID: AppUpdate884075538
    Result was: "Error"

**Comment by kungfu-king-betty** [comment]
Hello,
I apologize greatly for the wait on the response. I have released a new version (2.0.0) which should permanently fix this issue, if you are still using this plugin. Please let me know if you continue to have issues. I will leave this issue open for a while just in case.

**Comment by nicolasTorrell** [comment]
I installed the new version and now it says:
code: -3
message: "App Update Check Failed"
status: "error"

**Comment by kungfu-king-betty** [comment]
Hey @nicolasTorrell it looks like Android's In-App Updates library is failing for you for some reason. Would you mind looking in the debug logs and searching for E/NativeAppUpdate or just NativeAppUpdate and copying and pasting the error message and stack trace here? This will help greatly in tracking down the issue, and I will get this fixed for you as soon as possible.

**Comment by nicolasTorrell** [comment]
It gives me this error: E/NativeAppUpdate: com.google.android.play.core.install.InstallException: Install Error(-10): The app is not owned by any user on this device. An app is "owned" if it has been acquired from Play.
Does it only work if the app is downloaded from the PlayStore can't i test it with a debug app?

**Comment by mattkhaw** [comment]
> It gives me this error: E/NativeAppUpdate: com.google.android.play.core.install.InstallException: Install Error(-10): The app is not owned by any user on this device. An app is "owned" if it has been acquired from Play.
> Does it only work if the app is downloaded from the PlayStore can't i test it with a debug app?

For Android, it is required to use internal app sharing in order to utilise this feature. You can find more info through here -> [https://support.google.com/googleplay/android-developer/answer/9844679?hl=en](https://support.google.com/googleplay/android-developer/answer/9844679?hl=en)

I know this is kinda late but I encountered this problem too when I'm switching over to the newer version of this plugin.

**Comment by BenLaKnet** [comment]
I have the same problem with this version:
cordova-plugin-native-app-update 2.0.0 "AppUpdate"

What could I do now ?
